server:
  port: 80
  
spring:
  application:
    name: microservice-zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      
zuul:
  routes:
    api-web-demo:
      path: /web-demo/**
      serviceId: web-demo