server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/qianli_xy/microservice-config.git
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka/
