server:
  port: 80
  
spring:
  application:
    name: qianlixy-framework-microserver-eureka-server
    
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/