server:
  port: 8080
  
spring:
  application:
    name: qianlixy-framework-microserver-eureka-server
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/